const SUPABASE_URL='https://alxzmjgepftohwpqibmn.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseGptZ2VwdGZ0b3dwcWliZl9wcm9qZWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5OTg1NDQsImV4cCI6MjEwMTU3NDU0NH0.YvFQhCqL6spINPsyLs7lf7z5wxtnfi4U893ydWLXEaA'.replace('Ymx9cHJvamVjdC','bWVu');
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={session:null,profile:null,vendors:[],items:[],category:'all',cart:[],wish:new Set(),conversation:null,chatChannel:null,chatPoll:null};
function itemize(v){let x=v.items;if(typeof x==='string'){try{x=JSON.parse(x)}catch{return[]}}let a=[];if(Array.isArray(x))a=x.map((i,n)=>typeof i==='string'?{id:String(n),name:i,price:0,description:''}:{...i});else if(x&&typeof x==='object')a=Object.entries(x).map(([k,i])=>typeof i==='object'?{...i,id:String(i.id??k),name:String(i.name??i.title??k)}:{id:k,name:k,price:Number(i)||0});return a.map((i,n)=>({id:String(i.id??i.sku??n),name:String(i.name??i.title??'Item'),price:Number(i.price??i.amount??0),description:String(i.description??''),size:String(i.size??i.size_name??''),color:String(i.color??i.colour??''),category:String(i.category??v.subcategory??v.category??''),raw:i,vendorId:v.tonninyira_id,vendorName:v.business_name}));}
async function boot(){const {data}=await sb.auth.getSession();state.session=data.session;if(state.session)await hydrateUser();await loadCatalog();wire();render();}
async function hydrateUser(){let u=state.session.user;let {data:p}=await sb.from('profiles').select('display_name,phone,role').eq('id',u.id).maybeSingle();state.profile=p||{};await Promise.all([loadWish(),loadRewards(),loadOrders()]);}
async function loadCatalog(){let {data,error}=await sb.from('vendors_public').select('tonninyira_id,business_name,location,category,subcategory,logo_url,items,rating,reviews,years,latitude,longitude').order('business_name');if(error){$('market').innerHTML='<div class="panel">Marketplace unavailable. Please refresh.</div>';return}state.vendors=data||[];state.items=state.vendors.flatMap(itemize);populateFacets();}
function populateFacets(){const sizes=[...new Set(state.items.map(i=>i.size).filter(Boolean))].sort();const colors=[...new Set(state.items.map(i=>i.color).filter(Boolean))].sort();const s=$('sizeFilter'),c=$('colorFilter');s.innerHTML='<option value="">Any size</option>'+sizes.map(x=>`<option>${esc(x)}</option>`).join('');c.innerHTML='<option value="">Any colour</option>'+colors.map(x=>`<option>${esc(x)}</option>`).join('');}
function render(){const q=$('q').value.trim().toLowerCase(),min=Number($('minPrice').value||0),max=Number($('maxPrice').value||Infinity),size=$('sizeFilter').value,color=$('colorFilter').value,sort=$('sort').value,area=$('area').value;let a=state.items.filter(i=>{let v=state.vendors.find(v=>v.tonninyira_id===i.vendorId);let hay=[i.name,i.description,i.size,i.color,i.category,v?.business_name,v?.location,v?.category,v?.subcategory].join(' ').toLowerCase();return(!q||hay.includes(q))&&(state.category==='all'||hay.includes(state.category))&&(i.price>=min&&i.price<=max)&&(!size||i.size===size)&&(!color||i.color===color)&&(!area||String(v?.location||'').toLowerCase()===area.toLowerCase()||!area)});if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);let by=new Map();a.forEach(i=>{if(!by.has(i.vendorId))by.set(i.vendorId,[]);by.get(i.vendorId).push(i)});$('market').innerHTML=[...by.entries()].map(([vid,its])=>{let v=state.vendors.find(x=>x.tonninyira_id===vid);return `<article class="card"><div class="vendor"><div class="avatar">${v?.logo_url?`<img src="${esc(v.logo_url)}">`:esc((v?.business_name||'TN').slice(0,2).toUpperCase())}</div><div style="flex:1"><div class="name">${esc(v?.business_name)}</div><div class="small muted">${esc(v?.location||'')} · ${esc(v?.subcategory||v?.category||'Market')}</div><div class="verified">✓ Verified · ★ ${esc(v?.rating??'New')} · ${esc(v?.tonninyira_id)}</div></div><button class="heart" onclick="openVendor('${esc(vid)}')">View</button></div><div class="items">${its.slice(0,12).map(i=>`<div class="item"><div style="min-width:0"><div class="name">${esc(i.name)}</div><div class="small muted">${esc(i.description)}${i.size?' · '+esc(i.size):''}${i.color?' · '+esc(i.color):''}</div></div><div><div class="price">UGX ${i.price.toLocaleString()}</div><div class="actions"><button class="heart" onclick="toggleWish('${esc(i.vendorId)}','${esc(i.id)}','${esc(i.name)}')">${state.wish.has(i.vendorId+'|'+i.id)?'♥':'♡'}</button><button class="btn" onclick="addToCart('${esc(i.vendorId)}','${esc(i.vendorName)}','${esc(i.name)}',${i.price})">Add</button></div></div></div>`).join('')}</div></article>`}).join('')||'<div class="panel">No matching products. Adjust the filters.</div>';updateCart();}
function updateCart(){const n=state.cart.reduce((s,x)=>s+x.qty,0),t=state.cart.reduce((s,x)=>s+x.price*x.qty,0);$('cartCount').textContent=n;$('cartTotal').textContent='UGX '+t.toLocaleString();}
function addToCart(vendor_id,vendor_name,name,price){let x=state.cart.find(x=>x.vendor_id===vendor_id&&x.name===name);if(x)x.qty++;else state.cart.push({vendor_id,vendor_name,name,price,qty:1});updateCart();openPanel('cart');renderCart();}
function renderCart(){$('cartItems').innerHTML=state.cart.map((x,n)=>`<div class="row"><b>${esc(x.name)}</b><div class="small muted">${esc(x.vendor_name)} · UGX ${x.price.toLocaleString()} × ${x.qty}</div><div class="actions"><button class="heart" onclick="changeQty(${n},-1)">−</button><button class="heart" onclick="changeQty(${n},1)">+</button></div></div>`).join('')||'<div class="muted">Your basket is empty.</div>';updateCart();}
function changeQty(n,d){state.cart[n].qty+=d;if(state.cart[n].qty<=0)state.cart.splice(n,1);renderCart();}
async function checkout(){if(!state.session){openModal('auth');return}if(!state.cart.length)return;let phone=$('profilePhone').value.trim();if(!phone){openPanel('account');alert('Add your phone number before checkout.');return}await saveProfile(phone);let orderId='TN-'+Date.now().toString(36).toUpperCase();let groups={};state.cart.forEach(x=>(groups[x.vendor_id]??=[]).push({name:x.name,qty:x.qty}));for(const [vendor_id,items] of Object.entries(groups)){let v=state.vendors.find(x=>x.tonninyira_id===vendor_id);let {error}=await sb.from('orders').insert({order_id:orderId,vendor_id,vendor_name:v?.business_name,items,user_id:state.session.user.id,user_email:state.session.user.email,customer_name:state.profile.display_name||state.session.user.email,customer_phone:phone,delivery_area:$('area').value,delivery_option:'standard',payment_method:'cash_on_delivery',status:'pending',delivery_fee:0});if(error){alert(error.message);return}}state.cart=[];renderCart();closePanel('cart');await loadOrders();alert('Order placed: '+orderId);}
async function saveProfile(phone){const name=($('profileName').value||state.profile.display_name||state.session.user.email).trim();const {data:p}=await sb.from('profiles').upsert({id:state.session.user.id,display_name:name,phone,role:'customer',updated_at:new Date().toISOString()},{onConflict:'id'}).select('display_name,phone,role').single();state.profile=p||state.profile;}
async function loadWish(){let {data}=await sb.from('wishlists').select('vendor_id,item_id,item_name');state.wish=new Set((data||[]).map(x=>x.vendor_id+'|'+x.item_id));}
async function toggleWish(vendor_id,item_id,item_name){if(!state.session){openModal('auth');return}let k=vendor_id+'|'+item_id;if(state.wish.has(k))await sb.from('wishlists').delete().eq('vendor_id',vendor_id).eq('item_id',item_id);else await sb.from('wishlists').insert({user_id:state.session.user.id,vendor_id,item_id,item_name});await loadWish();render();renderSaved();}
function renderSaved(){let rows=[];state.wish.forEach(k=>{const [v,id]=k.split('|'),i=state.items.find(x=>x.vendorId===v&&x.id===id);if(i)rows.push(`<div class="row"><b>${esc(i.name)}</b><div class="small muted">${esc(i.vendorName)} · UGX ${i.price.toLocaleString()}</div><button class="btn" onclick="addToCart('${esc(i.vendorId)}','${esc(i.vendorName)}','${esc(i.name)}',${i.price})">Add to basket</button></div>`)});$('saved').innerHTML=rows.join('')||'<div class="muted">Nothing saved yet.</div>';}
async function loadRewards(){if(!state.session)return;let {data}=await sb.from('loyalty_accounts').select('points,lifetime_points').eq('user_id',state.session.user.id).maybeSingle();$('points').textContent=data?.points??0;$('lifetime').textContent=data?.lifetime_points??0;}
async function loadOrders(){if(!state.session)return;let {data}=await sb.from('orders').select('id,order_id,vendor_id,vendor_name,status,total,subtotal,created_at').eq('user_id',state.session.user.id).order('created_at',{ascending:false}).limit(20);state.orders=data||[];$('orders').innerHTML=state.orders.map(o=>`<div class="row"><b>${esc(o.order_id||o.id)}</b><div>${esc(o.vendor_name||'Vendor')} · <span class="status">${esc(o.status)}</span></div><div class="small muted">Total UGX ${Number(o.total??o.subtotal??0).toLocaleString()}</div>${o.status==='completed'?`<button class="heart" onclick="openReview('${esc(o.order_id)}','${esc(o.vendor_id)}')">Review</button>`:''}</div>`).join('')||'<div class="muted">No orders yet.</div>';}
async function openVendor(vendorId){let v=state.vendors.find(x=>x.tonninyira_id===vendorId);let {data:reviews}=await sb.from('reviews').select('rating,comment,reviewer_name,created_at').eq('target_type','vendor').eq('target_id',vendorId).order('created_at',{ascending:false}).limit(12);$('modalTitle').textContent=v?.business_name||'Vendor';$('modalBody').innerHTML=`<p class="muted">${esc(v?.location)} · ${esc(v?.category||'Market')}</p><h3>Reviews</h3>${(reviews||[]).map(r=>`<div class="row"><b>${'★'.repeat(Number(r.rating))}</b><div>${esc(r.comment||'')}</div><div class="small muted">${esc(r.reviewer_name||'Customer')}</div></div>`).join('')||'<div class="muted">No reviews yet.</div>'}<button class="btn" onclick="closeModal()">Close</button>`;openModal('info');}
let reviewOrderId=null,reviewVendorId=null;function openReview(oid,vid){reviewOrderId=oid;reviewVendorId=vid;openModal('review');}
async function submitReview(){if(!state.session)return;let rating=Number($('reviewRating').value),comment=$('reviewComment').value.trim();let {error}=await sb.from('reviews').insert({target_type:'vendor',target_id:reviewVendorId,order_id:reviewOrderId,user_id:state.session.user.id,reviewer_name:state.profile.display_name||'Customer',reviewer_phone:state.profile.phone||null,rating,comment});if(error)alert(error.message);else{alert('Review published.');closeModal();}}
async function ensureChat(){if(!state.session){openModal('auth');return null}if(state.conversation)return state.conversation;let {data}=await sb.from('support_conversations').select('id,status').eq('customer_id',state.session.user.id).eq('status','open').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!data){let r=await sb.from('support_conversations').insert({customer_id:state.session.user.id,status:'open'}).select('id,status').single();if(r.error){alert(r.error.message);return null}data=r.data}state.conversation=data;return data;}
async function openChat(){let c=await ensureChat();if(!c)return;openPanel('chat');await loadMessages();if(state.chatChannel)sb.removeChannel(state.chatChannel);state.chatChannel=sb.channel('support:'+c.id,{config:{private:true}}).on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages',filter:'conversation_id=eq.'+c.id},()=>loadMessages()).subscribe();}
async function loadMessages(){if(!state.conversation)return;let {data}=await sb.from('support_messages').select('id,sender_user_id,body,created_at').eq('conversation_id',state.conversation.id).order('created_at');$('messages').innerHTML=(data||[]).map(m=>`<div class="row"><b>${m.sender_user_id===state.session.user.id?'You':'Tonninyira Support'}</b><div>${esc(m.body)}</div><div class="small muted">${new Date(m.created_at).toLocaleString()}</div></div>`).join('')||'<div class="muted">Start the conversation.</div>';}
async function sendChat(){let body=$('chatInput').value.trim();if(!body||!(await ensureChat()))return;let {error}=await sb.from('support_messages').insert({conversation_id:state.conversation.id,sender_user_id:state.session.user.id,body});if(error)alert(error.message);else{$('chatInput').value='';await loadMessages();}}
async function sendOtp(){let email=$('email').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return alert('Enter a valid email.');let {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$('authMsg').textContent=error?error.message:'Check your email for the secure sign-in link.';}
async function logout(){await sb.auth.signOut();location.reload();}
function openModal(id){$(id).classList.remove('hidden')}function closeModal(){$$('.modal').forEach?null:null;document.querySelectorAll('.modal').forEach(x=>x.classList.add('hidden'))}function openPanel(id){$(id).classList.remove('hidden');if(id==='account'){$('profileName').value=state.profile?.display_name||'';$('profilePhone').value=state.profile?.phone||'';renderSaved()}}function closePanel(id){$(id).classList.add('hidden')}
function wire(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);$('account').onclick=()=>state.session?openPanel('account'):openModal('auth');$('cartBtn').onclick=()=>{openPanel('cart');renderCart()};$('checkout').onclick=checkout;$('chatBtn').onclick=openChat;$('sendChat').onclick=sendChat;$('sendReview').onclick=submitReview;$('sendOtp').onclick=sendOtp;$('logout').onclick=logout;$('saveProfile').onclick=async()=>{await saveProfile($('profilePhone').value.trim());alert('Profile saved.')};['q','minPrice','maxPrice','sort','sizeFilter','colorFilter','area'].forEach(id=>$(id).addEventListener('input',render));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');render()});$('shopNav').onclick=()=>{closePanel('account');closePanel('cart');window.scrollTo({top:0,behavior:'smooth'})};$('savedNav').onclick=()=>{openPanel('account');renderSaved();document.querySelector('#saved').scrollIntoView({behavior:'smooth'})};$('rewardsNav').onclick=()=>{openPanel('account');document.querySelector('#rewards').scrollIntoView({behavior:'smooth'})};$('ordersNav').onclick=()=>{openPanel('account');document.querySelector('#ordersPanel').scrollIntoView({behavior:'smooth'})};}
window.openVendor=openVendor;window.toggleWish=toggleWish;window.addToCart=addToCart;window.changeQty=changeQty;window.openReview=openReview;window.closeModal=closeModal;window.sendChat=sendChat;
window.addEventListener('DOMContentLoaded',boot);