const SUPABASE_URL='https://alxzmjgepftohwpqibmn.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseHptamdlcGZ0b3dwcWlibW4iLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc4NTk5ODU0NCwiZXhwIjoyMTAxNTc0NTQ0fQ.YvFQhCqL6spINPsyLs7lf7z5wxtnfi4U893ydWLXEaA';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={session:null,profile:{},vendors:[],items:[],category:'all',cart:[],wish:new Set(),conversation:null,channel:null,orders:[]};
function parseItems(v){let x=v.items;if(typeof x==='string'){try{x=JSON.parse(x)}catch{return[]}}let arr=[];if(Array.isArray(x))arr=x.map((i,n)=>typeof i==='string'?{id:String(n),name:i,price:0,description:''}:{...i});else if(x&&typeof x==='object')arr=Object.entries(x).map(([k,i])=>typeof i==='object'?{...i,id:String(i.id??k)}:{id:k,name:k,price:Number(i)||0});return arr.map((i,n)=>({id:String(i.id??i.sku??n),name:String(i.name??i.title??'Item'),price:Number(i.price??i.amount??0),description:String(i.description??''),size:String(i.size??i.size_name??''),color:String(i.color??i.colour??''),category:String(i.category??v.subcategory??v.category??''),vendorId:v.tonninyira_id,vendorName:v.business_name})).filter(i=>Number.isFinite(i.price));}
async function boot(){const r=await sb.auth.getSession();state.session=r.data.session;if(state.session)await hydrate();await loadCatalog();wire();render();updateAuth();}
async function hydrate(){const p=await sb.from('profiles').select('display_name,phone,role').eq('id',state.session.user.id).maybeSingle();state.profile=p.data||{};await Promise.all([loadWish(),loadRewards(),loadOrders()]);}
function updateAuth(){const b=$('account');b.textContent=state.session?'Account':'Sign in';$('accountState').textContent=state.session?'Signed in as '+(state.session.user.email||'customer'):'Sign in to save, order and earn rewards';$('logout').classList.toggle('hidden',!state.session);}
async function loadCatalog(){const r=await sb.from('vendors_public').select('tonninyira_id,business_name,location,category,subcategory,logo_url,items,rating,reviews,years,latitude,longitude').order('business_name');if(r.error){$('market').innerHTML='<div class="panel">Marketplace unavailable. Please refresh.</div>';return}state.vendors=r.data||[];state.items=state.vendors.flatMap(parseItems);const sizes=[...new Set(state.items.map(i=>i.size).filter(Boolean))].sort();const colors=[...new Set(state.items.map(i=>i.color).filter(Boolean))].sort();$('sizeFilter').innerHTML='<option value="">Any size</option>'+sizes.map(x=>`<option>${esc(x)}</option>`).join('');$('colorFilter').innerHTML='<option value="">Any colour</option>'+colors.map(x=>`<option>${esc(x)}</option>`).join('');}
function render(){const q=$('q').value.trim().toLowerCase(),min=Number($('minPrice').value||0),max=Number($('maxPrice').value||Infinity),size=$('sizeFilter').value,color=$('colorFilter').value,area=$('area').value;let list=state.items.filter(i=>{const v=state.vendors.find(x=>x.tonninyira_id===i.vendorId);const hay=[i.name,i.description,i.size,i.color,i.category,v?.business_name,v?.location,v?.category,v?.subcategory].join(' ').toLowerCase();return(!q||hay.includes(q))&&(state.category==='all'||hay.includes(state.category))&&i.price>=min&&i.price<=max&&(!size||i.size===size)&&(!color||i.color===color)&&(!area||String(v?.location||'').toLowerCase()===area.toLowerCase())});const sort=$('sort').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);const groups=new Map();list.forEach(i=>{if(!groups.has(i.vendorId))groups.set(i.vendorId,[]);groups.get(i.vendorId).push(i)});$('market').innerHTML=[...groups].map(([vid,items])=>{const v=state.vendors.find(x=>x.tonninyira_id===vid);const logo=v?.logo_url?`<img src="${esc(v.logo_url)}">`:esc((v?.business_name||'TN').slice(0,2).toUpperCase());return `<article class="card"><div class="vendor"><div class="avatar">${logo}</div><div style="flex:1"><div class="name">${esc(v?.business_name)}</div><div class="small muted">${esc(v?.location||'')} · ${esc(v?.subcategory||v?.category||'Market')}</div><div class="verified">✓ Verified · ★ ${esc(v?.rating??'New')}</div></div><button class="heart" data-vendor="${esc(vid)}" data-vendor-only="1">Reviews</button></div><div class="items">${items.slice(0,14).map(i=>`<div class="item"><div><div class="name">${esc(i.name)}</div><div class="small muted">${esc(i.description)}${i.size?' · '+esc(i.size):''}${i.color?' · '+esc(i.color):''}</div></div><div><div class="price">UGX ${i.price.toLocaleString()}</div><div class="actions"><button class="heart" data-wish="1" data-vendor="${esc(i.vendorId)}" data-item="${esc(i.id)}" data-name="${esc(i.name)}">${state.wish.has(i.vendorId+'|'+i.id)?'♥':'♡'}</button><button class="btn" data-add="1" data-vendor="${esc(i.vendorId)}" data-vendor-name="${esc(i.vendorName)}" data-name="${esc(i.name)}" data-price="${i.price}">Add</button></div></div></div>`).join('')}</div></article>`}).join('')||'<div class="panel">No matching products. Adjust the filters.</div>';updateCart();}
function updateCart(){const n=state.cart.reduce((s,x)=>s+x.qty,0),t=state.cart.reduce((s,x)=>s+x.price*x.qty,0);$('cartCount').textContent=n;$('cartTotal').textContent='UGX '+t.toLocaleString();}
function addToCart(vendor_id,vendor_name,name,price){const x=state.cart.find(a=>a.vendor_id===vendor_id&&a.name===name);if(x)x.qty++;else state.cart.push({vendor_id,vendor_name,name,price,qty:1});renderCart();openPanel('cart');}
function renderCart(){$('cartItems').innerHTML=state.cart.map((x,n)=>`<div class="row"><b>${esc(x.name)}</b><div class="small muted">${esc(x.vendor_name)} · UGX ${x.price.toLocaleString()} × ${x.qty}</div><div class="actions"><button class="heart" data-cart-index="${n}" data-cart-delta="-1">−</button><button class="heart" data-cart-index="${n}" data-cart-delta="1">+</button></div></div>`).join('')||'<div class="muted">Your basket is empty.</div>';updateCart();}
function changeQty(n,d){if(!state.cart[n])return;state.cart[n].qty+=d;if(state.cart[n].qty<=0)state.cart.splice(n,1);renderCart();}
async function checkout(){if(!state.session){openModal('auth');return}if(!state.cart.length)return;const phone=String($('profilePhone').value||state.profile.phone||'').trim();if(!phone){openPanel('accountPanel');return alert('Add your phone number before checkout.')}await saveProfile();const orderId='TN-'+Date.now().toString(36).toUpperCase();const groups={};state.cart.forEach(x=>(groups[x.vendor_id]??=[]).push({name:x.name,qty:x.qty}));for(const [vendor_id,items] of Object.entries(groups)){const v=state.vendors.find(x=>x.tonninyira_id===vendor_id);const r=await sb.from('orders').insert({order_id:orderId,vendor_id,vendor_name:v?.business_name,items,user_id:state.session.user.id,user_email:state.session.user.email,customer_name:state.profile.display_name||state.session.user.email,customer_phone:phone,delivery_area:$('area').value,delivery_option:'standard',payment_method:'cash_on_delivery',status:'pending',delivery_fee:0});if(r.error)return alert(r.error.message)}state.cart=[];renderCart();closePanel('cart');await loadOrders();alert('Order placed: '+orderId);}
async function saveProfile(){const name=String($('profileName').value||state.profile.display_name||state.session.user.email).trim(),phone=String($('profilePhone').value||'').trim();const r=await sb.from('profiles').upsert({id:state.session.user.id,display_name:name,phone,role:'customer',updated_at:new Date().toISOString()},{onConflict:'id'}).select('display_name,phone,role').single();if(r.error)return alert(r.error.message);state.profile=r.data;updateAuth();}
async function loadWish(){if(!state.session)return;const r=await sb.from('wishlists').select('vendor_id,item_id,item_name');state.wish=new Set((r.data||[]).map(x=>x.vendor_id+'|'+x.item_id));}
async function toggleWish(vendor_id,item_id,item_name){if(!state.session)return openModal('auth');const k=vendor_id+'|'+item_id;const r=state.wish.has(k)?await sb.from('wishlists').delete().eq('vendor_id',vendor_id).eq('item_id',item_id):await sb.from('wishlists').insert({user_id:state.session.user.id,vendor_id,item_id,item_name});if(r.error)return alert(r.error.message);await loadWish();renderSaved();render();}
function renderSaved(){let html='';for(const k of state.wish){const [v,id]=k.split('|'),i=state.items.find(x=>x.vendorId===v&&x.id===id);if(i)html+=`<div class="row"><b>${esc(i.name)}</b><div class="small muted">${esc(i.vendorName)} · UGX ${i.price.toLocaleString()}</div><button class="btn" data-save-add-v="${esc(i.vendorId)}" data-save-add-n="${esc(i.vendorName)}" data-save-add-name="${esc(i.name)}" data-save-add-price="${i.price}">Add to basket</button></div>`}$('saved').innerHTML=html||'<div class="muted">Nothing saved yet.</div>';}
async function loadRewards(){if(!state.session)return;const r=await sb.from('loyalty_accounts').select('points,lifetime_points').eq('user_id',state.session.user.id).maybeSingle();$('points').textContent=r.data?.points??0;$('lifetime').textContent=r.data?.lifetime_points??0;}
async function loadOrders(){if(!state.session)return;const r=await sb.from('orders').select('id,order_id,vendor_id,vendor_name,status,total,subtotal,created_at').eq('user_id',state.session.user.id).order('created_at',{ascending:false}).limit(20);state.orders=r.data||[];$('orders').innerHTML=state.orders.map(o=>`<div class="row"><b>${esc(o.order_id||String(o.id))}</b><div>${esc(o.vendor_name||'Vendor')} · ${esc(o.status)}</div><div class="small muted">UGX ${Number(o.total??o.subtotal??0).toLocaleString()}</div>${o.status==='completed'?`<button class="heart" data-review-order="${esc(o.order_id)}" data-review-vendor="${esc(o.vendor_id)}">Review</button>`:''}</div>`).join('')||'<div class="muted">No orders yet.</div>';}
async function openVendor(vid){const v=state.vendors.find(x=>x.tonninyira_id===vid);const r=await sb.from('reviews').select('rating,comment,reviewer_name,created_at').eq('target_type','vendor').eq('target_id',vid).order('created_at',{ascending:false}).limit(12);$('modalTitle').textContent=v?.business_name||'Vendor';$('modalBody').innerHTML=`<p class="muted">${esc(v?.location||'')} · ${esc(v?.category||'Market')}</p>${(r.data||[]).map(x=>`<div class="row"><b>${'★'.repeat(Number(x.rating))}</b><div>${esc(x.comment||'')}</div><div class="small muted">${esc(x.reviewer_name||'Customer')}</div></div>`).join('')||'<div class="muted">No verified reviews yet.</div>'}`;openModal('info');}
let reviewOrder='',reviewVendor='';function openReview(orderId,vendorId){if(!state.session)return openModal('auth');reviewOrder=orderId;reviewVendor=vendorId;openModal('review');}
async function submitReview(){if(!state.session)return;const r=await sb.from('reviews').insert({target_type:'vendor',target_id:reviewVendor,order_id:reviewOrder,user_id:state.session.user.id,reviewer_name:state.profile.display_name||'Customer',reviewer_phone:state.profile.phone||null,rating:Number($('reviewRating').value),comment:$('reviewComment').value.trim()});if(r.error)return alert(r.error.message);closeModal();await loadCatalog();}
async function ensureChat(){if(!state.session){openModal('auth');return null}if(state.conversation)return state.conversation;let r=await sb.from('support_conversations').select('id,status').eq('customer_id',state.session.user.id).eq('status','open').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!r.data){r=await sb.from('support_conversations').insert({customer_id:state.session.user.id,status:'open'}).select('id,status').single()}if(r.error){alert(r.error.message);return null}state.conversation=r.data;return r.data;}
async function openChat(){const c=await ensureChat();if(!c)return;openPanel('chat');await loadMessages();if(state.channel)sb.removeChannel(state.channel);state.channel=sb.channel('support:'+c.id,{config:{private:true}}).on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages',filter:'conversation_id=eq.'+c.id},loadMessages).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setTimeout(loadMessages,5000);});}
async function loadMessages(){if(!state.conversation)return;const r=await sb.from('support_messages').select('id,sender_user_id,body,created_at').eq('conversation_id',state.conversation.id).order('created_at');$('messages').innerHTML=(r.data||[]).map(m=>`<div class="row"><b>${m.sender_user_id===state.session.user.id?'You':'Tonninyira Support'}</b><div>${esc(m.body)}</div><div class="small muted">${new Date(m.created_at).toLocaleString()}</div></div>`).join('')||'<div class="muted">No messages yet.</div>';}
async function sendChat(){const body=$('chatInput').value.trim(),c=await ensureChat();if(!c||!body)return;const r=await sb.from('support_messages').insert({conversation_id:c.id,sender_user_id:state.session.user.id,body});if(r.error)alert(r.error.message);else{$('chatInput').value='';await loadMessages();}}
async function sendOtp(){const email=$('email').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return alert('Enter a valid email.');const r=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$('authMsg').textContent=r.error?'Sign-in failed: '+r.error.message:'Check your email for the secure sign-in link.';}
function openModal(id){$(id).classList.remove('hidden')}function closeModal(){document.querySelectorAll('.modal').forEach(x=>x.classList.add('hidden'))}function openPanel(id){$(id).classList.remove('hidden');if(id==='accountPanel'){$('profileName').value=state.profile.display_name||'';$('profilePhone').value=state.profile.phone||'';renderSaved();loadRewards();loadOrders();updateAuth();}}function closePanel(id){$(id).classList.add('hidden')}
function wire(){document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);$('account').onclick=()=>state.session?openPanel('accountPanel'):openModal('auth');$('cartBtn').onclick=()=>{openPanel('cart');renderCart();};$('checkout').onclick=checkout;$('chatBtn').onclick=openChat;$('sendChat').onclick=sendChat;$('sendReview').onclick=submitReview;$('sendOtp').onclick=sendOtp;$('saveProfile').onclick=saveProfile;$('logout').onclick=()=>sb.auth.signOut().then(()=>location.reload());['q','minPrice','maxPrice','sizeFilter','colorFilter','sort','area'].forEach(id=>$(id).addEventListener('input',render));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');render();});$('market').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add)addToCart(b.dataset.vendor,b.dataset.vendorName,b.dataset.name,Number(b.dataset.price));else if(b.dataset.wish)toggleWish(b.dataset.vendor,b.dataset.item,b.dataset.name);else if(b.dataset.vendorOnly)openVendor(b.dataset.vendor);});$('cartItems').addEventListener('click',e=>{const b=e.target.closest('button[data-cart-index]');if(b)changeQty(Number(b.dataset.cartIndex),Number(b.dataset.cartDelta));});$('saved').addEventListener('click',e=>{const b=e.target.closest('button[data-save-add-v]');if(b)addToCart(b.dataset.saveAddV,b.dataset.saveAddN,b.dataset.saveAddName,Number(b.dataset.saveAddPrice));});$('orders').addEventListener('click',e=>{const b=e.target.closest('button[data-review-order]');if(b)openReview(b.dataset.reviewOrder,b.dataset.reviewVendor);});$('savedNav').onclick=()=>{openPanel('accountPanel');setTimeout(()=>$('savedPanel').scrollIntoView({behavior:'smooth'}),0)};$('rewardsNav').onclick=()=>{openPanel('accountPanel');setTimeout(()=>$('rewardsPanel').scrollIntoView({behavior:'smooth'}),0)};$('ordersNav').onclick=()=>{openPanel('accountPanel');setTimeout(()=>$('ordersPanel').scrollIntoView({behavior:'smooth'}),0)};$('accountNav').onclick=()=>openPanel('accountPanel');$('shopNav').onclick=()=>{closePanel('accountPanel');closePanel('cart');scrollTo({top:0,behavior:'smooth'});}}
sb.auth.onAuthStateChange(async(_e,s)=>{state.session=s;if(s)await hydrate();updateAuth();render();});
window.addEventListener('DOMContentLoaded',boot);
Object.assign(window,{openVendor,toggleWish,addToCart,changeQty,openReview,sendChat,renderCart});